# only ctc
# conformer7 -> onlyctc
encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 15

    num_sd_blocks: 4
    num_joint_blocks: 2
    num_rec_blocks:  6

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

ctc_conf:
    ignore_nan_grad: true
    reduce: false

num_workers: 4
unused_parameters: True
batch_type: numel
batch_bins: 17500000  # 17.5M*2 = 35M
#batch_bins: 1000000  # org: 35000000
accum_grad: 4 
grad_clip: 5
max_epoch: 35
val_scheduler_criterion:
    - valid
    - loss
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.0005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
